export enum ExceptionCode {
	UNAUTHORIZED = "ERROR.UNAUTHORIZED",
	FORBIDDEN = "ERROR.FORBIDDEN",
	INTERNAL_SERVER_ERROR = "ERROR.INTERNAL",
	BAD_REQUEST_ERROR = "ERROR.BAD_REQUEST",
	NOT_FOUND = "ERROR.NOT_FOUND"
}
